# 服务器端口号
server:
  port: 8080

spring:
  profiles:
    active: dev
    #active: prod
  main:
    allow-bean-definition-overriding: true





ftp:
  hostname: 127.0.0.1
  port: 21
  username: root
  password: because
  directory: /root

